language: c
matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - label=default
      before_install: &bs
        - docker pull kazuho/h2o-ci:latest
        - docker build -t ci -f misc/docker-ci/Dockerfile .
      script:
        - docker run ci
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - label=fuzz
      before_install: *bs
      script:
        - docker run ci make -f misc/docker-ci/check.mk fuzz
