sudo: required
language: c
services:
  - docker
before_install:
  - docker build -t h2o-ci -f misc/docker-ci/Dockerfile .
script:
  - docker run h2o-ci make check
  - docker run h2o-ci sudo make check-as-root
