language: c
dist: xenial
sudo: required

matrix:
  include:
    - name: Linux (gcc-8)
      os: linux
      compiler: gcc-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8']
    - name: Linux (clang)
      os: linux
      compiler: clang
    - name: macOS (Xcode)
      os: osx
      env:
          - CMAKE_OPTS=" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"
    - name: macOS (Xcode 10.1/clang-10)
      os: osx
      osx_image: xcode10.1
      env:
          - CMAKE_OPTS=" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"

before_install:

script:
  - cmake ${CMAKE_OPTS} .
  - make all
  - make check
