name: CI/default

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      shell: 'script -q -e -c "bash {0}"'
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk
