name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  dtrace:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk dtrace CONTAINER_NAME=h2oserver/h2o-ci:ubuntu2004
