name: CI

on:
  - push
  - pull_request

jobs:
  default:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk
  openssl_1_1_0:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk ossl1.1.0
  openssl_1_1_1:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk ossl1.1.1
  fuzz:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk fuzz
  dtrace:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run with Docker
      run: |
        chmod -R ugo+w .
        make -f misc/docker-ci/check.mk dtrace CONTAINER_NAME=h2oserver/h2o-ci:ubuntu2004
